version: 1
runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

handlers:

- url: /(.*\.(html|css|js))
  static_files: app/\1
  upload: app/(.*\.(html|css|js))

- url: /
  static_files: app/index.html
  upload: app/index.html

- url: /.*
  script: app.js
  login: required
