runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

handlers:

- url: /(.*\.(png|jpg|woff))$
  static_files: app/\1
  upload: app/.*\.(png|jpg|woff)$

- url: .*
  script: dynamic
