version: 1
runtime: custom
vm: true
api_version: 1
threadsafe: yes

manual_scaling:
  instances: 1

handlers:

# Node
#- url: /(.*\.(html|css|js))
#  static_files: app/\1
#  upload: app/(.*\.(html|css|js))

- url: /(.*\.(html|css|js|gif|png|jpg))$
  static_files: app/\1
  upload: app/.*\.(html|css|js|gif|png|jpg)$

- url: /
  static_files: app/index.html
  upload: app/index.html

- url: .*
  script: dynamic

# Node
#- url: /.*
#  script: app.js
#  login: required
