version: 1
runtime: custom
vm: true
api_version: 1

# Java?
threadsafe: yes

manual_scaling:
  instances: 1

handlers:

# Node
#- url: /(.*\.(html|css|js))
#  static_files: app/\1
#  upload: app/(.*\.(html|css|js))

# Java
- url: /(.*\.(gif|png|jpg))$
  static_files: app/\1
  upload: app/.*\.(gif|png|jpg)$

# Node
#- url: /
#  static_files: app/index.html
#  upload: app/index.html

# Java
- url: .*
  script: dynamic

# Node
#- url: /.*
#  script: app.js
#  login: required
