runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

handlers:

- url: /(.*\.(gif|png|jpg|woff|map))$
  static_files: app/\1
  upload: app/.*\.(gif|png|jpg|woff|map)$

- url: .*
  script: dynamic
